### ISSUE TITLE
get_user_ptr_finalizer and set_user_ptr_finalizer should use emacs_finalizer_function

### ISSUE THREAD

**Issue by tromey** [aaptel/emacs-dynamic-module#27]
Right now these two declarations look like:

```
  void (*(*get_user_ptr_finalizer)(emacs_env *env, emacs_value uptr))(void *) EMACS_NOEXCEPT;
  void (*set_user_ptr_finalizer)(emacs_env *env,
                                 emacs_value uptr,
                                 void (*fin)(void *) EMACS_NOEXCEPT);
```

The first especially is pretty ugly!

I think using the existing `emacs_finalizer_function` typedef here would be much clearer.

**Comment by phst** [comment]
I introduced this change to improve safety with modules written in C++. Declaring them this way means that finalizers written in C++ must be declared `noexcept`, i.e. they can't throw exceptions (which would very likely lead to UB because the Emacs C code isn't prepared for that). I agree that it's ugly, but unfortunately there's no other way to guarantee this property.

**Comment by tromey** [comment]
I think you can do this like:

```
typedef void (*finalizer)(void*);
void set_it (finalizer noexcept);
```

**Comment by phst** [comment]
No, unfortunately that's also invalid.

**Comment by phst** [comment]
I've asked this on https://groups.google.com/a/isocpp.org/d/msg/std-discussion/a2Xh9cErkq4/52NxSlZHAwAJ, but unfortunately until the C++ standard gets changed there's little we can do. I'll add a comment to `emacs_module.h` though.
