### ISSUE TITLE
add docstring to make_function

### ISSUE THREAD

**Issue by tromey** [aaptel/emacs-dynamic-module#30]
I think it would be handy if the make_function method let me pass in a docstring.  RIght now I don't see a good way to do this.

**Comment by phst** [comment]
I initially thought this would clutter the interface too much, but now I think this could make sense because it would be similar to other function definition facilities. Aurélien, WDYT?

**Comment by aaptel** [comment]
It could be part of the libemacs but it can also be in the API I guess. I think we should really start that lib otherwise we are going to put everything in the API. Should we have a separate defvar call to be similar to the rest of Emacs?

We have to document that the docstring must be UTF8 encoded. They also need to have a particular format (basically respect elisp conventions).

**Comment by tromey** [comment]
I tend to think it should be part of the base API, since we want to encourage module developers to also supply doc strings.

I think defvar doesn't matter as much, because -- unless the module API supports `(require)` directly -- most modules will come with a `.el` as well, and the defvar can just be done there.

**Comment by phst** [comment]
Putting this into an extension API would make it harder to implement and would make it impossible to switch the implementation to a subr, should we ever want that. The extension API would have to check whether the function is indeed a lambda, check whether it already has a docstring, and otherwise attach the docstring using `(setcdr (cdr x) (cons "docstring" (cddr x)))`, whereas the base API could just put it directly into the lambda form.

**Comment by aaptel** [comment]
> unless the module API supports (require) directly

Yep, you can require modules.

Variable documentation can be done using `(put my-var variable-documentation "My doc")`. It's simple enough to do with the current API I guess it can be moved to the lib.

**Comment by phst** [comment]
`defvar` can also be called directly from modules. Nothing stops you from doing the C equivalent of executing `(eval '(defvar foo 42 "docstring") t)`. The same is not true for functions that are supposed to call C code, therefore we have `make_function`, but not `make_variable`.

**Comment by aaptel** [comment]
Let's add this then. I'm adding it to the milestone.
