### ISSUE TITLE
Maybe remove argument count checks

### ISSUE THREAD

**Issue by phst** [aaptel/emacs-dynamic-module#39]
Module functions currently resemble subrs in that their definition includes argument count specifications (`{min,max}_arity`). However, internally they are represented using lambdas, and e.g. `subr-arity` doesn't work for them. The argument count check could be removed. This would force module authors to do argument count checks themselves, though.

**Comment by tromey** [comment]
It's been rather convenient to have the checks done for me, but it's ok if this has to go away.

Converting to real `Lisp_Subr` objects might be nice (and good enough in most cases), though they'd have to grow a little in order to accommodate the `data` field.  Not clear if that would be acceptable upstream; though I'd imagine the bloat is small.

**Comment by aaptel** [comment]
I also really like the check done in Emacs. Module functions are not subr, it doesnt bother me if _subr_-arity doesn't work. Alternatively we could construct the lamba form in `make_function` directly with the right prototype.

**Comment by phst** [comment]
OK, let's keep the checks then.
